version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node-type-orm
        ports:
            - '4000:4000'
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - PORT=4000
        command: sh -c "yarn install && yarn start"
